"""fitur absent

Revision ID: 234ce2c2ba04
Revises: 0725a760370d
Create Date: 2026-09-30 07:42:56.574551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234ce2c2ba04'
down_revision: Union[str, Sequence[str], None] = '0725a760370d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_pw', sa.String(length=200), nullable=False),
    sa.Column('call_name', sa.String(length=25), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=True),
    sa.Column('class_', sa.String(length=10), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('nis', sa.String(length=20), nullable=True),
    sa.Column('phone_number', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nis'),
    sa.UniqueConstraint('username')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Hadir', 'Sakit', 'Izin', 'Alpa', 'Terlambat', name='status_enum'), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('user_latitude', sa.String(), nullable=True),
    sa.Column('user_longitude', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('users_id', 'date', name='unique_attendance_per_day')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    op.drop_table('users')
    # ### end Alembic commands ###
