"""test3?

Revision ID: 7e735c786bbb
Revises: e4754a6a0c1b
Create Date: 2026-10-01 00:41:35.299834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e735c786bbb'
down_revision: Union[str, Sequence[str], None] = 'e4754a6a0c1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('date_insert', sa.Date(), nullable=False))
    op.drop_constraint(op.f('unique_attendance_per_day'), 'attendance', type_='unique')
    op.create_unique_constraint('unique_attendance_per_day', 'attendance', ['users_id', 'date_insert'])
    op.drop_column('attendance', 'date_inserts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('date_inserts', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint('unique_attendance_per_day', 'attendance', type_='unique')
    op.create_unique_constraint(op.f('unique_attendance_per_day'), 'attendance', ['users_id', 'date_inserts'], postgresql_nulls_not_distinct=False)
    op.drop_column('attendance', 'date_insert')
    # ### end Alembic commands ###
