"""benerin attendance dikit

Revision ID: ed79f0743123
Revises: 234ce2c2ba04
Create Date: 2026-09-30 21:53:12.928898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed79f0743123'
down_revision: Union[str, Sequence[str], None] = '234ce2c2ba04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('date_inserts', sa.Date(), nullable=False))
    op.drop_constraint(op.f('unique_attendance_per_day'), 'attendance', type_='unique')
    op.create_unique_constraint('unique_attendance_per_day', 'attendance', ['users_id', 'date_inserts'])
    op.drop_column('attendance', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint('unique_attendance_per_day', 'attendance', type_='unique')
    op.create_unique_constraint(op.f('unique_attendance_per_day'), 'attendance', ['users_id', 'date'], postgresql_nulls_not_distinct=False)
    op.drop_column('attendance', 'date_inserts')
    # ### end Alembic commands ###
